{
    'name': 'Gym Member',
    'version': '2.1',
    'author': 'AMS Logic',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'web', 'board'],
    'data': [
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/sequence_data.xml',
        'data/cron_jobs.xml',
        'data/mail_templates.xml',
        'data/demo_data.xml',
        'views/gym_membership_views.xml',
        'views/payment_views.xml',
        'views/attendance_views.xml',
        'views/class_views.xml',
        'reports/member_report.xml',
        'reports/payment_report.xml',
        'views/menu_views.xml',
        'wizards/member_export_wizard.xml',
        'wizards/bulk_email_wizard.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}